version: "2.1"
services:
  jenkins:
    build: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 133 #docker group id
    networks:
      - tools
  tomcat:
    build: tomcat
    networks:
      - tools
  nexus:
    image: sonatype/nexus3:latest
    networks:
      - tools
    volumes:
      - nexus-data:/nexus-data
  sonaqube:
    image: sonarqube:latest
    networks:
      - tools
  nginx:
    build: nginx
    ports:
      - 8080:8080
      - 443:443
    networks:
      - tools
networks:
  tools:
#    name: tools
# naming the tools network seems to be unsupported on my remote machine
# docker-compose version 1.17.1, build unknown
# docker-py version: 2.5.1
# CPython version: 2.7.17
# OpenSSL version: OpenSSL 1.1.1  11 Sep 2018 

volumes:
  jenkins_home:
    name: jenkins_home
    #external: true
  nexus-data:
    name: nexus-data
    #external: true
