version: "2.1"
services:
  jenkins:
    build: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 133 #docker group id
    networks:
      - tools
  tomcat:
    build: tomcat
    networks:
      - tools
  nexus:
    image: sonatype/nexus3:latest
    networks:
      - tools
    volumes: 
      - nexus-data:/nexus-data
  sonaqube:
    image: sonarqube:latest
    networks:
      - tools
  nginx:
    build: tomcat
    ports: 
      - 80:80
      - 443:443
    networks:
      - tools
networks:
  tools:
volumes:
  jenkins_home:
  nexus-data:
